### ISSUE TITLE
TLYShyNavBar header not compatible with MJRefresh

### ISSUE THREAD

**Issue by tuantmdev** [telly/TLYShyNavBar#100]
In my project, i used both of those libraries but i got 1 issue with refresh header. It appears under navigation bar (maybe the content offset or content size of uitableview changed when using TLYShyNavBar).

Before using TLYShyNavBar

![Before integrate with TLYShyNavBar](http://i.imgur.com/LITZui0.png)

After using TLYShyNavBar. The loading icon show under nav bar

![After integrate with TLYShyNavBar](http://i.imgur.com/yTvVD6y.png)

Any idea to fix this? Thanks so much!

**Comment by Mazyod** [comment]
Thanks for reporting this. This library constantly updates the bounds of the tableView to ensure the table view is displayed properly, so maybe both libraries need to have some autonomy over the bounds calculation. If that is the case, I am afraid it won't be possible to fix, since coordination between the two libraries is needed.

In any case, I'll look into it, and maybe I can suggest a way to work around the issue within your own code.

**Comment by tuantmdev** [comment]
Thanks so much

**Comment by Mazyod** [comment]
Thanks for reporting this .. It is directly related to #99. I am looking into that issue right now, and fixing that will hopefully fix your issue. Please subscribe to that issue for updates!
