### ISSUE TITLE
ScrollView inside of Container View

### ISSUE THREAD

**Issue by curiousurick** [telly/TLYShyNavBar#110]
So my situation is a little weird. I have a CAPSPageMenu that contains 4 UITableViewControllers. I wondered how I should set this up so that the menu moves up with the fading of the nav bar until it reaches the top, and then let the table view continuing the scrolling.

**Comment by Mazyod** [comment]
@curiousurick I regret to say that `UITableViewControllers` is not supported with the latest release because it does some magic behind the scenes relating to the bounds and scrolling, ultimately messing up the library. So, if you're looking to use this library, you would have to try an earlier version like `0.10.1` or better replace the `UITableViewControllers`.

**Comment by curiousurick** [comment]
Okay, so if it just used UIViewControllers with UITableViews, what would I do here?

**Comment by Mazyod** [comment]
Ah, regarding the CAPSPageMenu, I don't think it would be possible to use this library. In order to make this library as easy to use as possible, it connects with `UINavigationBar` behind the scenes, and you can't really have a custom bar from some custom library.

After looking at CAPSPageMenu, it is really ideal if that library supported the functionality you are after inherently, since it also has the tabs view which would probably be handled in a customizable way.

**Comment by curiousurick** [comment]
So do you think it's not possible or that I would have to modify one of the libraries to support it? Because I was hoping there would be a way to see the current `UIViewController`'s `UITableView` delegate to the shynavbar and it would scroll but all it does is hide the navigation bar, it doesn't move the menu up. I've tried placing the whole thing in a custom scrollview but I'm not very adept with scroll views and my subviews have been getting misplaced.

**Comment by Mazyod** [comment]
It's just the design decision for this library to be tightly coupled with `UINavigationController` hierarchy to simplify the integration steps. You may make use of the actual code in some other way, or go a completely different route, but I don't think there is any quick solution.
