### ISSUE TITLE
the lib is not working correctly with SVPullToRefresh

### ISSUE THREAD

**Issue by lethanhclub** [telly/TLYShyNavBar#133]
I am using both SVPullToRefresh & TLYShyNavBar. But the pull to refresh function is not working anymore

**Comment by nonamelive** [comment]
I found that if you comment out the following code in `TLYShyScrollViewController.m`, it will work with SVPullToRefresh.

```
//        if (self.refreshControl == nil || [self.refreshControl isHidden]) {
//            [self.scrollView tly_setInsets:insets];
//        }

```

**Comment by lethanhclub** [comment]
you will get wrong contentInset after scrolling the table view with it

**Comment by arielpollack** [comment]
The issue here is that they enter an infinite loop of updating the scrollView's content size/inset.
This partial stack trace is a crash log we're receiving, and the original crash log is 10 times longer (meaning it performed the same methods over and over again in a cycle)
![image](https://cloud.githubusercontent.com/assets/1862153/14101696/bbf9f7f4-f59e-11e5-8770-669491eb9187.png)
