### ISSUE TITLE
Use TLYShyNavBar with ASyncDisplayKit ASCollectionNode

### ISSUE THREAD

**Issue by simoami** [telly/TLYShyNavBar#158]
I faced an issue when attempting to hook the TLYShyNavBar with ASDK views. They have an alternative to the delegate property called asyncDelegate. As shown in their [docs](http://asyncdisplaykit.org/docs/containers-ascollectionnode.html). When hooking a scrollView i get a runtime error stating that delegate is not a supported property, use asyncDelegate instead.

Any chance I can manually configure the delegate binding so to avoid the runtime error?

**Comment by Mazyod** [comment]
Thanks for reporting the issue. There is already an issue about supporting ASDK here #72 

In general, I am against supporting different libraries, because this component is *by design* tightly coupled to UIKit. That's why it only takes a single line of code to get started. But if we were to generalize the component for different UI libraries, it will need more configuration to work.

Anyways, if you fork this repo and try to make it work for ASDK, just ping me with any questions and I'll try my best to help.

**Comment by simoami** [comment]
Thanks @Mazyod I'll look into this and let you know if I need help.
