### ISSUE TITLE
Issue with plain table view with sections and search bar in header

### ISSUE THREAD

**Issue by dron4eeek** [telly/TLYShyNavBar#17]
Hello, I am using component on view with tableview witch have refresh control, searchbar in header, sections and index bar. 
The issue is that table header goes under white gap when nav bar scrolls up, the sections issue that they stop under standart navigation bar place.
Wich solution can I use here?

Thank you!

**Comment by jwardle** [comment]
+1

**Comment by marcocattai** [comment]
+1 

- when used with a UISearchBar/SearchDisplayController it doesn't work properly. 

There is no way cancel the contraction of the navBar when the user tap on UISearchBar while the navBar is hiding with its animation because the tableView was scrolling. The UISearchDisplayController will show its TableView but the NavigationBar with the searchBar is now hidden.

**Comment by stefanomondino** [comment]
+1

**Comment by efremidze** [comment]
+1
