### ISSUE TITLE
Flickering extension view when scrolling

### ISSUE THREAD

**Issue by alexandergmacleod** [telly/TLYShyNavBar#39]
When scrolling to the top of a UITableView with a reasonable amount of force, the extension view would sometimes flicker. I have attached a video of what I'm seeing via Dropbox:

https://dl.dropboxusercontent.com/u/1319151/Screencast.mov

Any ideas?

**Comment by skela** [comment]
I have the same problem.

**Comment by Mazyod** [comment]
@Silvercast I am guessing your navigation bar background is opaque, and doesn't show the extension view when it's tucked behind the navbar. That's not always the case, unfortunately, so the extension view has to be set to `hidden` when it exceeds a certain threshold.

**Comment by skela** [comment]
Not really sure what you mean @Mazyod , I've tried @Silvercast 's suggestion and it does remove the flickering and I've got a translucent navigation bar and extension view. Can't see any unwanted side-effects in my setup atm. Maybe that bit of code was needed before but isn't anymore?

**Comment by Mazyod** [comment]
@skela The telly app gif in the readme is a "translucent" navbar, but it has a solid background since we set the background as an opaque image. But what if the developer has a truly translucent navbar, like the one in the demo?

I think the value `0` for a float might not be appropriate. If you can please test `FLT_EPSILON` or `0.1f`. If that works, it will help a lot if you could also submit a PR.

**Comment by skela** [comment]
I've tried it both with FLT_EPSILON and 0.1f and it removed the flickering in both cases. I'll make a pull request with that change :D

**Comment by Silvercast** [comment]
Great. Looking forward to test the new version @skela @Mazyod

**Comment by Mazyod** [comment]
Should be done now, thanks to the guys contributions
