### ISSUE TITLE
UITableView shows black bar with an opaque navbar

### ISSUE THREAD

**Issue by fabb** [telly/TLYShyNavBar#63]
In my case, the UIScrollView is contained in a Container View, as I change the Container View contents according to some setting.

The View Hierarchy looks like this:
```
ViewControllerView
|-> ContainerView
    |-> ContainerViewControllerView
        |-> TableView
```

I configure `shyNavBarManager` with the `TableView`. The nav bar gets hidden fine when the table view is scrolled, but the table view frame (or rather the `ContainerView` frame) is not adapted. The nav bar hides, but leaves a black space.

I guess the library expects the table view being a direct child view of the view controller's view?

**Comment by fabb** [comment]
BTW I have an opaque nav bar.

**Comment by Mazyod** [comment]
Thanks for the report. I can't directly comment on opaque navbars, seems people have some success using them, but the library doesn't directly support it yet. See #7 

As for the container, you might have to roll your custom code that expands the container view, since it's expected that the container will not scale automatically as the navbar collapses.

Last note, I am not saying your issue is not related to the component at all, it would be better if the component can adapt to your situation ..  but for the time being, you might have manually handle the issue.

**Comment by Mortenest** [comment]
I have a very similar issue.
In my case however, I don't care whether I have a opaque navigation bar or not, and the size of the embedded viewcontroller is as big as it's superview.

I think this framework is really great, but it would be even better with support for this.
 
@fabb Did you find out how to solve the issue?

Thanks

**Comment by fabb** [comment]
@mortenest: sorry, unfortunately not

**Comment by mthole** [comment]
Just as an FYI, I ran into this issue today as well. I'll probably roll my own. Would be great to have the support here, though! (Looks like a great library, kudos.)
