### ISSUE TITLE
NavBar disappear with delay

### ISSUE THREAD

**Issue by mutaliskBLR** [telly/TLYShyNavBar#67]
When I set in ViewWillDisappear which contains TLYShyNavBar [[self navigationController] setNavigationBarHidden:YES animated:NO];
On next viewController nav bar disappears with delay, after POP animation ends.

**Comment by Mazyod** [comment]
Can you please try using `viewWillAppear` to manage navigation bar appearance instead? It is more appropriate to do it there.

So, instead of calling `[[self navigationController] setNavigationBarHidden:YES animated:NO];` inside the view controller with the `shyNavBarManager`, make the call in the first view controller's `viewWillAppear`.
