### ISSUE TITLE
Buttons on the extension view are not working

### ISSUE THREAD

**Issue by zhifeng-huang** [telly/TLYShyNavBar#84]
I have two UIButtons on the extension view. When the extension view is not moved up, the buttons are working fine. When the extension view is shifted up (stick to the top), the buttons are not working anymore. Any idea?

**Comment by dbleicher** [comment]
I don't have a solution, but I have seen this problem as well and may have some insight.  Short version:  everything works if I avoid using autolayout constraints in the extensionview.  

I'm using an collectionview with a custom extensionview containing two buttons (one far left, one far right) with a label between them.  In the viewController, I use initWithFrame to instantiate the extensionview from a XIB that uses AutoLayout, and then I use setExtensionView to add it to the shyNavBarManager:

    // TLYShyNav
    self.extendedLayoutIncludesOpaqueBars = YES;
    self.shyNavBarManager.scrollView = self.collectionView;
    self.shyNavBarManager.expansionResistance = 0;
    self.shyNavBarManager.contractionResistance = 0;

    self.qrBar = [[MessageListQRBar alloc] initWithFrame:
                  CGRectMake(0,
                             0,
                             self.view.bounds.size.width,
                             self.navigationController.navigationBar.bounds.size.height)];

    [self.shyNavBarManager setExtensionView:self.qrBar];


1. In all cases, the extensionview appears/displays properly
2. In all cases, my far left button works as expected
3. The right-hand button does not work at all

Here are some things I've noticed:

1. If I scroll the collectionview down and then up, so that the extensionview is visible but is over one of the collectionview items, clicking on my right-button actually selects the collectionview item underneath.  I believe the reason my right button never works is that the underlying collectionview is always receiving its touch events. (Without scrolling, the events are going to the collectionview's empty background).
2.  If I eliminate all AutoLayout constraints from the extensionview's XIB, all buttons work exactly as expected.  There is a conflict in my autolayout constraints that, I believe, is causing the problem above.

Don't know how to fix this yet, but hopefully the above will be helpful in finding a solution.

**Comment by zhifeng-huang** [comment]
My extension view does not have any auto layout constraints.

**Comment by joshbernfeld** [comment]
Go into TLYShyNavBarManager.m and change the following line in init

    self.extensionViewContainer.autoresizingMask = UIViewAutoresizingFlexibleWidth|UIViewAutoresizingFlexibleBottomMargin;
 
To this

    self.extensionViewContainer.autoresizingMask = UIViewAutoresizingFlexibleBottomMargin;

This should be categorized as a bug because the buttons work fine on iPhone 6 but any screen size of 320 the autoresizing mask shortens the view and limits the clickable region on the right hand side.

**Comment by dbleicher** [comment]
@joshbernfeld I tried your suggestion, but it didn't resolve the issue in my case.  I have discovered a workaround, at least for my issue.  I'm using a universal storyboard and loading my extension view from a custom XIB (see code above) in viewDidLoad for my VC.  Turns out that the autolayout issues above were a red herring.  

My problem occurred when buttons in my extensionview are on the right side of the screen, when the screen-width is greater than iPhone portrait (e.g. iPhone landscape, and any iPad resolution).  Basically, buttons on the left work, buttons beyond mid-screen do not (touch event passes through to the view below the extensionview).  I've worked around this by making the XIB for my extensionview 1024 points (max for iPad), and including a transparent view (0p high, 1024p wide) in that view.  After doing this, all my autolayout and buttons work in any position on the extensionview, and in any resolution.  I use autolayout to scale down for the iPhones, but this is working on all device layouts now.

**Comment by Mazyod** [comment]
@zhifeng-huang I updated the test with a button that you can test and see how it works.

@joshbernfeld Thanks for your suggestion, but I don't believe it's a bug in the library. Why shouldn't the extension view resize its width? I don't think the issue you described is applicable, since the `extensionViewContainer` inherits the `bounds` from the extension view. So, try setting the `extensionView`'s frame before assigning it?

@dbleicher Glad it worked out :)

**Comment by dbleicher** [comment]
@Mazyod as long as my extensionview contains a full-width (e.g. 1024p wide), life is grand.  Deployed in production today with no problems.  TLYShyNavBar is awesome!

**Comment by vineeth90** [comment]
I am also facing the same issue. I am creating the elements in extensionView through code and does not use xib / storyboard / autoLayout at all. Still my buttons are not working when extensionView is shifted. Any of the above solutions worked for me. 
Any suggestions / fixes guys ?
