### ISSUE TITLE
Web View Inset Not Working Properly with Top-Fixed Elements

### ISSUE THREAD

**Issue by insanj** [telly/TLYShyNavBar#96]
Elements which are top-fixed in web views (in this case a `WKWebView`) will not properly anchor to the top of the "shy" web view. Anything which pins itself via CSS to the top of the view will float where the full-height nav bar would be when TLYShyNavBar pushes it away.

This does not occur using different "shy" bar implementations, such as Apple's own in Safari and SFSafariViewController.

![example](https://cloud.githubusercontent.com/assets/951011/11106979/6b685100-88a7-11e5-9626-e06d9258b774.PNG)

**Comment by Mazyod** [comment]
Yeah, this all has to do with updating the `contentInsts` to exactly match the visible area. Would fix `UITableView` headers as well, and probably many other use cases. I spent the whole night yesterday trying to figure it out, but `UITableView` is just weird.

Maybe I'll push the fix for the sake of at least resolving issues like this, and leave `UITableView` for another chapter.
